version: "2"
services:
  app:
    build: .
    command: stack exec hree-example
    working_dir: $PWD
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - "$PWD:$PWD"
      - .stack:/root/.stack
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
