version: "2"
services:
  app:
    build: .
    working_dir: $PWD
    environment:
      - DISPLAY=${DISPLAY}
      - MESA_GL_VERSION_OVERRIDE=4.5
      - MESA_GLSL_VERSION_OVERRIDE=450
    volumes:
      - "$PWD:$PWD"
      - .stack:/root/.stack
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
