name:                hree
version:             0.1.0.0
github:              "githubuser/hree"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hree#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- bytestring
- containers
- file-embed
- gl
- gl-wrapper
- hashable
- hashtables
- linear
- mwc-random
- text
- transformers
- vector

library:
  source-dirs: src

internal-libraries:
  examples-common:
    source-dirs: examples-common
    dependencies:
    - hree
    - GLFW-b

executables:
  flat-color-1:
    main:                Main.hs
    source-dirs:         examples/flat-color-1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - examples-common
    - hree
    - GLFW-b

  texture-1:
    main:                Main.hs
    source-dirs:         examples/texture-1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - examples-common
    - hree
    - GLFW-b

  geometry-box-1:
    main:                Main.hs
    source-dirs:         examples/geometry-box-1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - examples-common
    - hree
    - GLFW-b

  transform-rotate-1:
    main:                Main.hs
    source-dirs:         examples/transform-rotate-1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - examples-common
    - hree
    - GLFW-b

  sprite-instanced-1:
    main:                Main.hs
    source-dirs:         examples/sprite-instanced-1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - examples-common
    - hree
    - GLFW-b

tests:
  hree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - hspec
    - GLFW-b
    extra-libraries:
    - OSMesa
