name:                hree
version:             0.1.0.0
github:              "githubuser/hree"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hree#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- aeson
- attoparsec
- binary
- bytestring
- base64-bytestring
- cereal
- containers
- directory
- filepath
- file-embed
- gl
- gl-wrapper
- hashable
- hashtables
- linear
- mwc-random
- text
- transformers
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wtabs

library:
  source-dirs: src

executables:
  flat-color-1:
    main:                Main.hs
    source-dirs:
    - examples/flat-color-1
    - examples-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - GLFW-b

  texture-1:
    main:                Main.hs
    source-dirs:
    - examples/texture-1
    - examples-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - GLFW-b

  geometry-box-1:
    main:                Main.hs
    source-dirs:
    - examples/geometry-box-1
    - examples-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - GLFW-b

  transform-rotate-1:
    main:                Main.hs
    source-dirs:
    - examples/transform-rotate-1
    - examples-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - GLFW-b

  sprite-instanced-1:
    main:                Main.hs
    source-dirs:
    - examples/sprite-instanced-1
    - examples-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - GLFW-b

  format-loader-1:
    main:                Main.hs
    source-dirs:
    - examples/format-loader-1
    - examples-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - GLFW-b

  gltf-minimal-1:
    main:                Main.hs
    source-dirs:
    - examples/gltf-minimal-1
    - examples-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - GLFW-b

  child-node-1:
    main:                Main.hs
    source-dirs:
    - examples/child-node-1
    - examples-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - GLFW-b

  standard-material-1:
    main:                Main.hs
    source-dirs:
    - examples/standard-material-1
    - examples-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - GLFW-b

tests:
  hree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hree
    - hspec
    - GLFW-b
    extra-libraries:
    - OSMesa
