name:                hree
version:             0.6.0
github:              "tkaaad97/hree"
license:             BSD3

flags:
  examples:
    manual: true
    default: false
  embed_shaders:
    manual: false
    default: true

data-files:
  - shader/**/*.glsl

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs

dependencies:
  - base >= 4.7 && < 5
  - JuicyPixels >=3.2.9.5 && <3.4
  - aeson >=1.2.4.0 && <1.6
  - atomic-primops >=0.8 && <0.9
  - attoparsec >=0.13.2.2 && <0.14
  - base64-bytestring >=1.0.0.0 && <1.2
  - bytestring >=0.9.2.1 && <0.11
  - cereal >=0.4.1.1 && <0.6
  - chronos >=1.1 && <1.2
  - containers >=0.4.2.1 && <0.7
  - directory >=1.3.0 && <1.4
  - file-embed >=0.0.10 && <0.1
  - filepath >=1.3 && <1.5
  - gl >=0.9 && <0.10
  - gl-wrapper >=0.9 && <0.10
  - hashable >=1.2.7.0 && <1.4
  - hashtables >=1.2.2.0 && <1.3
  - linear >=1.10.1.2 && <1.22
  - mwc-random >=0.11 && <0.15
  - template-haskell >=2.7 && <3.0
  - text >=1.2.3.0 && <1.3
  - transformers >=0.3.0.0 && <0.6
  - unordered-containers >=0.2.8.0 && <0.3
  - vector >=0.12.0.1 && <0.13
  - vector-algorithms >=0.7.0.1 && <0.9
  - zlib >=0.5.3.1 && <0.7

library:
  ghc-options:
    - -O2
  source-dirs: src
  when:
    - condition: flag(embed_shaders)
      then:
        cpp-options: -DEMBED_SHADERS
      else:
        generated-other-modules: Paths_hree

_exe-common: &exe-common
  when:
    - condition: flag(examples)
      then:
        source-dirs:
          - examples
        other-modules:
          - Example
        dependencies:
          - hree
          - GLFW-b
      else:
        buildable: false

executables:
  child-node-1:
    <<: *exe-common
    main:                ChildNode1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - ChildNode1

  flat-color-1:
    <<: *exe-common
    main:                FlatColor1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - FlatColor1

  format-loader-1:
    <<: *exe-common
    main:                FormatLoader1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - FormatLoader1

  geometry-box-1:
    <<: *exe-common
    main:                GeometryBox1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - GeometryBox1

  gltf-minimal-1:
    <<: *exe-common
    main:                GLTFMinimal1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - GLTFMinimal1

  node-mesh-animation-1:
    <<: *exe-common
    main:                NodeMeshAnimation1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - NodeMeshAnimation1

  skinning-1:
    <<: *exe-common
    main:                Skinning1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - Skinning1

  sprite-instanced-1:
    <<: *exe-common
    main:                SpriteInstanced1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - SpriteInstanced1

  standard-material-1:
    <<: *exe-common
    main:                StandardMaterial1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - StandardMaterial1

  texture-1:
    <<: *exe-common
    main:                Texture1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - Texture1

  tiled-1:
    <<: *exe-common
    main:                Tiled1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - Tiled1

  transform-rotate-1:
    <<: *exe-common
    main:                TransformRotate1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - TransformRotate1

  uv-animation-1:
    <<: *exe-common
    main:                UvAnimation1.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - UvAnimation1

  uv-animation-2:
    <<: *exe-common
    main:                UvAnimation2.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is
      - UvAnimation2

tests:
  hree-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hree
    - hspec
    - GLFW-b
    - QuickCheck
    extra-libraries:
    - OSMesa
