name: build on windows

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: build with ghc-${{ matrix.ghc }}

    env:
      STACK_YAML: stack-ghc-${{ matrix.ghc }}.yaml
      STACK_ROOT: "${{ github.workspace }}\\.stack"

    strategy:
      matrix:
        ghc:
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          #- "8.8.3"

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: cache ${{ env.STACK_ROOT }}
        uses: actions/cache@v2
        with:
          path: ${{ env.STACK_ROOT }}
          key: windows-ghc-${{ matrix.ghc }}-stack-${{ hashFiles('**/package.yaml') }}
          restore-keys: |
            windows-ghc-${{ matrix.ghc }}-stack-

      - name: build draco
        run: ./scripts/build-draco.sh third_party/draco

      - name: build
        run: stack build --extra-include-dirs=./third_party/draco/src:./third_party/draco/build --extra-lib-dirs=./third_party/draco/build --flag hree:enable_draco --flag hree:examples --no-test

      - name: build with no embed_shaders flag
        run: stack build --extra-include-dirs=./third_party/draco/src:./third_party/draco/build --extra-lib-dirs=./third_party/draco/build --flag hree:enable_draco --flag hree:examples --flag hree:-embed_shaders --no-test
